<a href="https://colab.research.google.com/github/boleamol/NLP/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Word Embedding by using Keras**

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [15]:
### sentences
sent=[  'that so kind of you',
     'please help yourself',
     'how dare you',
    'sorry for the inconvenience',
     'would you please speak slowly',
     'how are you',
     'i am so happy',]

In [16]:
sent

['that so kind of you',
 'please help yourself',
 'how dare you',
 'sorry for the inconvenience',
 'would you please speak slowly',
 'how are you',
 'i am so happy']

In [17]:
voc_size=10000   # We can declare vocabulary size of any.

In [18]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr) # printing one hot representation 

[[7049, 867, 6726, 8851, 1596], [9414, 8928, 2146], [2828, 1769, 1596], [9507, 8647, 9557, 3007], [3913, 1596, 9414, 4015, 6940], [2828, 3048, 1596], [960, 5667, 867, 5155]]


In [19]:
sent_length=8   # Here we fixed sentence length 
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) # If sentence is not having 8 words then it add/pad 0, that is also beginning
print(embedded_docs)

[[   0    0    0 7049  867 6726 8851 1596]
 [   0    0    0    0    0 9414 8928 2146]
 [   0    0    0    0    0 2828 1769 1596]
 [   0    0    0    0 9507 8647 9557 3007]
 [   0    0    0 3913 1596 9414 4015 6940]
 [   0    0    0    0    0 2828 3048 1596]
 [   0    0    0    0  960 5667  867 5155]]


In [20]:
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse') # Mean Squared Error (MSE) is perhaps the simplest and most common loss function

In [22]:
model.summary() # Printing model summary

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
print(model.predict(embedded_docs))

[[[-0.01914982  0.02306614  0.02978195  0.03138024 -0.02968606
   -0.03692942 -0.0170873   0.03575914  0.0284223   0.04464639]
  [-0.01914982  0.02306614  0.02978195  0.03138024 -0.02968606
   -0.03692942 -0.0170873   0.03575914  0.0284223   0.04464639]
  [-0.01914982  0.02306614  0.02978195  0.03138024 -0.02968606
   -0.03692942 -0.0170873   0.03575914  0.0284223   0.04464639]
  [ 0.02852556 -0.01137745  0.03427705  0.02584643  0.02633103
    0.01939005 -0.02422286 -0.02879254 -0.03612892  0.00629718]
  [ 0.03391938  0.02558427  0.02266787  0.01425078 -0.02839488
   -0.0447568   0.01094358  0.03481329  0.03504679  0.04021521]
  [ 0.0005375  -0.00511948  0.02479434 -0.01026299  0.02391051
   -0.03986859 -0.04682764 -0.02523936  0.00095256 -0.01980927]
  [-0.03602283 -0.02940604 -0.04150368  0.03256797  0.02058723
   -0.03674241  0.03495009  0.00711931 -0.031145    0.0418235 ]
  [-0.00082161  0.04669621 -0.04468146 -0.04373255 -0.02047124
    0.04182385  0.04510057 -0.00777329  0.049065

In [24]:
embedded_docs[0]    # Printing first sentence.

array([   0,    0,    0, 7049,  867, 6726, 8851, 1596], dtype=int32)

In [25]:
print(model.predict(embedded_docs)[0])  # Printing Vectors

[[-0.01914982  0.02306614  0.02978195  0.03138024 -0.02968606 -0.03692942
  -0.0170873   0.03575914  0.0284223   0.04464639]
 [-0.01914982  0.02306614  0.02978195  0.03138024 -0.02968606 -0.03692942
  -0.0170873   0.03575914  0.0284223   0.04464639]
 [-0.01914982  0.02306614  0.02978195  0.03138024 -0.02968606 -0.03692942
  -0.0170873   0.03575914  0.0284223   0.04464639]
 [ 0.02852556 -0.01137745  0.03427705  0.02584643  0.02633103  0.01939005
  -0.02422286 -0.02879254 -0.03612892  0.00629718]
 [ 0.03391938  0.02558427  0.02266787  0.01425078 -0.02839488 -0.0447568
   0.01094358  0.03481329  0.03504679  0.04021521]
 [ 0.0005375  -0.00511948  0.02479434 -0.01026299  0.02391051 -0.03986859
  -0.04682764 -0.02523936  0.00095256 -0.01980927]
 [-0.03602283 -0.02940604 -0.04150368  0.03256797  0.02058723 -0.03674241
   0.03495009  0.00711931 -0.031145    0.0418235 ]
 [-0.00082161  0.04669621 -0.04468146 -0.04373255 -0.02047124  0.04182385
   0.04510057 -0.00777329  0.04906538 -0.01471025]]
